version: '3.1'

services:

  # Web
  web:
    build:
      context: ./.docker/
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./app:/var/www/html
    networks:
      - laravel

  # Database
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data: